version: "3"

services:
  webapp:
    build: ./webapp/
    depends_on:
      - db
    command: php -S 0.0.0.0:80
    ports:
      - "${WEB_APP_PORT}:80"
  db:
    build: ./db/
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  jenkins:
    build: ./jenkins/
    ports:
      - "${JENKINS_PORT}:8080"
    depends_on:
      - sonarqube
    environment:
      JENKINS_ADMIN_ID: root
      JENKINS_ADMIN_PASSWORD: root
      JENKIN_PORT: ${JENKINS_PORT}
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      hive-network:
        aliases:
          - jenkins
  sonarqube:
    build: ./sonarqube/
    image: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - hive-network

volumes:
  jenkins-data:
  mysql-data:

networks:
  hive-network: